In [1]:
!pip install pandas

Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.3.3)
Requirement already satisfied: numpy>=1.17.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (1.21.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

In [3]:
#reading the daily new infections from csv dataset (not yet clipped to our target timeframe)
Infectiondf = pd.read_csv('./Israel_Infection_Translated_Original.csv')

In [4]:
Infectiondf.head()

,Date,Age,Infection-Vaccinated,Vaccinated without Validity,Infection-Not Vaccinated,"Infection-Vaccinated per 100,000 residents","Vaccinated without Validity per 100,000 residents","Infection-Not Vaccinated per 100,000 residents"
0,17-01-2021,מתחת לגיל 60,1,0,4436,6.4,0.0,66.6
1,17-01-2021,מעל גיל 60,0,0,243,0.0,0.0,51.4
2,17-01-2021,כלל האוכלוסיה,1,0,4715,3.9,0.0,66.1
3,18-01-2021,מעל גיל 60,4,0,346,19.8,0.0,74.2
4,18-01-2021,מתחת לגיל 60,2,0,8288,7.9,0.0,125.7

In [5]:
#cleaning the infection dataframe, dropping the unnecessary columns and rows.
Infectiondf = Infectiondf[np.arange(len(Infectiondf)) % 3 == 2]
Infectiondf.drop(["Age",'Infection-Vaccinated per 100,000 residents',
                  'Vaccinated without Validity per 100,000 residents',
                 'Infection-Not Vaccinated per 100,000 residents'], 
                 axis = 1, inplace = True)
Infectiondf.reset_index(drop=True, inplace=True)

Infectiondf

,Date,Infection-Vaccinated,Vaccinated without Validity,Infection-Not Vaccinated
0,17-01-2021,1,0,4715
1,18-01-2021,6,0,8715
2,19-01-2021,9,0,7330
3,20-01-2021,18,0,7157
4,21-01-2021,8,0,301
...,...,...,...,...
312,25-11-2021,64,46,394
313,26-11-2021,76,57,397
314,27-11-2021,23,20,125
315,28-11-2021,86,53,384
316,29-11-2021,7,6,6

In [6]:
#During this period Alpha is the dominant variant
#Establish the daily new infection dataset for this 'Alpha Period' Only (2021/01/17 - 2021/03/06)
InfectionAlphaDf = Infectiondf[0:49] 
InfectionAlphaDf

,Date,Infection-Vaccinated,Vaccinated without Validity,Infection-Not Vaccinated
0,17-01-2021,1,0,4715
1,18-01-2021,6,0,8715
2,19-01-2021,9,0,7330
3,20-01-2021,18,0,7157
4,21-01-2021,8,0,301
5,22-01-2021,18,0,255
6,23-01-2021,5,0,1870
7,24-01-2021,9,0,3859
8,25-01-2021,73,0,7389
9,26-01-2021,95,0,6611
10,27-01-2021,78,0,262
11,28-01-2021,174,0,5879
12,29-01-2021,130,0,5571
13,30-01-2021,37,0,2143
14,31-01-2021,59,0,158
15,01-02-2021,130,0,287
16,02-02-2021,95,0,6209
17,03-02-2021,86,0,5779
18,04-02-2021,120,0,252
19,05-02-2021,77,0,5086
20,06-02-2021,34,0,133
21,07-02-2021,138,0,3632
22,08-02-2021,107,0,286
23,09-02-2021,148,0,5074
24,10-02-2021,55,0,4469
25,11-02-2021,46,0,3996
26,12-02-2021,51,0,3667
27,13-02-2021,29,0,1579
28,14-02-2021,35,0,2680
29,15-02-2021,66,0,4107
30,16-02-2021,38,0,3592
31,17-02-2021,100,0,3410
32,18-02-2021,75,0,2741
33,19-02-2021,75,0,3083
34,20-02-2021,25,0,1014
35,21-02-2021,23,0,131
36,22-02-2021,111,0,3917
37,23-02-2021,107,0,3521
38,24-02-2021,62,0,3261
39,25-02-2021,32,0,137
40,26-02-2021,27,0,118
41,27-02-2021,32,0,1010
42,28-02-2021,105,0,2229
43,01-03-2021,88,0,3525
44,02-03-2021,41,0,133
45,03-03-2021,150,0,3480
46,04-03-2021,141,0,2750
47,05-03-2021,44,0,95
48,06-03-2021,26,0,64

In [7]:
#save the cleaned dataset to file
Infectiondf.to_csv('Israel_Infection.csv')
InfectionAlphaDf.to_csv('Israel_Infection_Alpha_Period.csv')

In [8]:
#opening and reading the vaccination data (not yet clipped to our target timeframe)
Vaccinationsdf = pd.read_csv('./Israel_Vaccination_Translated_Original.csv')

In [9]:
Vaccinationsdf.head()

,Date,First_Dose_Counts,Second_Dose_Counts,Third_Dose_Counts,First_Dose_Percentage,Second_Dose_Percentage,Third_Dose_Percetage,Percentage_Not_Vaccinated,Percentage_of_Invalid_Vaccinations,Percentage_of_Vaccinated
0,19-12-2020,65,1,0,0.00,0.0,0.0,100.0,0.0,0.0
1,20-12-2020,7450,1,0,0.08,0.0,0.0,100.0,0.0,0.0
2,21-12-2020,32357,1,0,0.35,0.0,0.0,100.0,0.0,0.0
3,22-12-2020,76990,1,0,0.83,0.0,0.0,100.0,0.0,0.0
4,23-12-2020,139878,1,0,1.50,0.0,0.0,100.0,0.0,0.0

In [10]:
#cleaning the Vaccinationsdf Dataset, dropping the unnecessary columns

Vaccinationsdf.drop(["First_Dose_Counts",'Second_Dose_Counts',
             "Third_Dose_Counts", "Percentage_Not_Vaccinated",
             "Percentage_of_Invalid_Vaccinations", "Percentage_of_Vaccinated"], 
                 axis = 1, inplace = True)



Vaccinationsdf

,Date,First_Dose_Percentage,Second_Dose_Percentage,Third_Dose_Percetage
0,19-12-2020,0.00,0.00,0.00
1,20-12-2020,0.08,0.00,0.00
2,21-12-2020,0.35,0.00,0.00
3,22-12-2020,0.83,0.00,0.00
4,23-12-2020,1.50,0.00,0.00
...,...,...,...,...
342,26-11-2021,67.77,62.08,43.75
343,27-11-2021,67.82,62.08,43.76
344,28-11-2021,67.93,62.10,43.81
345,29-11-2021,68.03,62.11,43.86
346,30-11-2021,68.09,62.12,43.88

In [11]:
#The daily counts of people vaccinated as a  percentage of the Israeli population is clipped to 
#only include the rows related to our analysis.
#However, we take considerations of the fact that
#the antibody give by vaccine takes two weeks to reach its maximum

# Extract the data  for the target timeframe (two weeks before 2021/01/17) - (two weeks before 2021/03/06)
Vaccinationsdf = Vaccinationsdf[15:64]

Vaccinationsdf.reset_index(drop=True, inplace=True)

Vaccinationsdf

,Date,First_Dose_Percentage,Second_Dose_Percentage,Third_Dose_Percetage
0,03-01-2021,13.81,0.00,0.0
1,04-01-2021,15.45,0.00,0.0
2,05-01-2021,16.79,0.00,0.0
3,06-01-2021,17.90,0.00,0.0
4,07-01-2021,19.15,0.00,0.0
5,08-01-2021,19.86,0.00,0.0
6,09-01-2021,20.34,0.00,0.0
7,10-01-2021,20.75,0.06,0.0
8,11-01-2021,20.97,0.27,0.0
9,12-01-2021,21.23,0.66,0.0
10,13-01-2021,21.79,1.27,0.0
11,14-01-2021,22.40,2.01,0.0
12,15-01-2021,22.73,2.39,0.0
13,16-01-2021,23.04,2.67,0.0
14,17-01-2021,23.78,3.58,0.0
15,18-01-2021,24.53,4.88,0.0
16,19-01-2021,25.31,6.36,0.0
17,20-01-2021,26.13,7.90,0.0
18,21-01-2021,26.89,9.67,0.0
19,22-01-2021,27.29,10.43,0.0
20,23-01-2021,27.72,11.01,0.0
21,24-01-2021,28.46,12.52,0.0
22,25-01-2021,29.33,14.02,0.0
23,26-01-2021,30.18,15.38,0.0
24,27-01-2021,31.02,16.72,0.0
25,28-01-2021,31.87,18.12,0.0
26,29-01-2021,32.26,18.82,0.0
27,30-01-2021,32.63,19.28,0.0
28,31-01-2021,33.42,19.92,0.0
29,01-02-2021,34.31,20.30,0.0
30,02-02-2021,35.06,20.63,0.0
31,03-02-2021,35.71,21.18,0.0
32,04-02-2021,36.49,21.81,0.0
33,05-02-2021,36.85,22.12,0.0
34,06-02-2021,37.08,22.36,0.0
35,07-02-2021,37.66,23.09,0.0
36,08-02-2021,38.29,23.80,0.0
37,09-02-2021,39.01,24.52,0.0
38,10-02-2021,39.76,25.30,0.0
39,11-02-2021,40.63,26.07,0.0
40,12-02-2021,41.05,26.48,0.0
41,13-02-2021,41.35,26.80,0.0
42,14-02-2021,42.15,27.54,0.0
43,15-02-2021,43.03,28.36,0.0
44,16-02-2021,43.93,29.20,0.0
45,17-02-2021,44.59,30.01,0.0
46,18-02-2021,45.33,30.87,0.0
47,19-02-2021,45.76,31.28,0.0
48,20-02-2021,46.10,31.58,0.0

In [12]:
# Saved the cleaned vaccination dataframe to file
Vaccinationsdf.to_csv('Israel_Vaccination_Data_Alpha_Period.csv')

In [13]:
#opening and reading the completed original data of daily tests to estimate the population "p" at risk of infection
DailyTestsdf = pd.read_csv('./Israel_Daily_Tests_Translated_Original.csv')

In [14]:
DailyTestsdf.head()

         Date  Number_of_Virus_Discovery  Number_of_Speed_Tests  Total_tests
0  20-02-2020                         29                      0           29
1  21-02-2020                         28                      0           28
2  22-02-2020                         13                      0           13
3  23-02-2020                         56                      0           56
4  24-02-2020                         74                      0           74

In [15]:
# cleaning the daily tests data set to included only the dates in our target timeframe
DailyTestsdf = DailyTestsdf[332:381]

DailyTestsdf.reset_index(drop=True, inplace=True)

DailyTestsdf

          Date  Number_of_Virus_Discovery  Number_of_Speed_Tests  Total_tests
0   17-01-2021                      63376                      0        63376
1   18-01-2021                     100611                      0       100611
2   19-01-2021                      94663                      0        94663
3   20-01-2021                      91832                      0        91832
4   21-01-2021                      81169                      0        81169
5   22-01-2021                      84649                      0        84649
6   23-01-2021                      30429                      0        30429
7   24-01-2021                      53503                      0        53503
8   25-01-2021                      89948                      0        89948
9   26-01-2021                      82173                      0        82173
10  27-01-2021                      84646                      0        84646
11  28-01-2021                      77257                      0        77257
12  29-01-2021                      73047                      0        73047
13  30-01-2021                      26392                      0        26392
14  31-01-2021                      54035                      0        54035
15  01-02-2021                      91474                      0        91474
16  02-02-2021                      87269                      0        87269
17  03-02-2021                      84737                      0        84737
18  04-02-2021                      83104                      0        83104
19  05-02-2021                      82844                      0        82844
20  06-02-2021                      28472                      0        28472
21  07-02-2021                      52899                      0        52899
22  08-02-2021                      89667                      0        89667
23  09-02-2021                      79451                      7        79458
24  10-02-2021                      76030                      0        76030
25  11-02-2021                      75116                      0        75116
26  12-02-2021                      66314                      0        66314
27  13-02-2021                      24430                      0        24430
28  14-02-2021                      46409                      0        46409
29  15-02-2021                      69587                      0        69587
30  16-02-2021                      72770                      0        72770
31  17-02-2021                      63305                      0        63305
32  18-02-2021                      51339                      0        51339
33  19-02-2021                      61834                      0        61834
34  20-02-2021                      19200                      0        19200
35  21-02-2021                      49038                      0        49038
36  22-02-2021                      68201                      0        68201
37  23-02-2021                      70499                      0        70499
38  24-02-2021                      73695                      0        73695
39  25-02-2021                      69217                      0        69217
40  26-02-2021                      64799                      0        64799
41  27-02-2021                      24037                      0        24037
42  28-02-2021                      53610                      0        53610
43  01-03-2021                      88060                      0        88060
44  02-03-2021                      89235                      0        89235
45  03-03-2021                      92344                      0        92344
46  04-03-2021                      88795                      0        88795
47  05-03-2021                      99564                      0        99564
48  06-03-2021                      40484                      0        40484

In [16]:
#saving this cleaned dataframe for daily tests to csv file
DailyTestsdf.to_csv('Israel_Daily_Tests_Data_Alpha_Period.csv')

In [17]:
!pip install statsmodels

Requirement already satisfied: statsmodels in /srv/conda/envs/notebook/lib/python3.7/site-packages (0.13.0)
Requirement already satisfied: scipy>=1.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.7.1)
Requirement already satisfied: pandas>=0.25 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.3.3)
Requirement already satisfied: numpy>=1.17 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.21.2)
Requirement already satisfied: patsy>=0.5.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (0.5.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2021.3)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)

In [18]:
#setup the contigency table for proportion-testing vaccine efficacy against severe cases
#it seems like there aren't enough data for analyzing vaccince efficacy against infection

In [19]:
from statsmodels.stats.proportion import proportions_ztest

In [20]:
#This variable gives the mean of daily infections who are vaccinated for the 49-day timeframe
Daily_Cases_Vaccinated_Alpha = (InfectionAlphaDf["Infection-Vaccinated"]).mean()
Daily_Cases_Vaccinated_Alpha

66.10204081632654

In [21]:
#This variable gives the mean of daily infections who are NOT vaccinated for the 49-day timeframe
Daily_Cases_Not_Vaccinated_Alpha = (InfectionAlphaDf["Infection-Not Vaccinated"]).mean()
Daily_Cases_Not_Vaccinated_Alpha

3013.5102040816328

In [22]:
#This variable gives the mean size of the population at risk for the 49-day timeframe
Daily_Polulation_at_Risk_Alpha = (DailyTestsdf["Total_tests"]).mean()

Daily_Polulation_at_Risk_Alpha

68685.02040816327

In [23]:
#This variable gives the mean vaccination percentage of the Israeli population for the 49-day timeframe
#However we take consideration of the fact the antibody givein Pfizer vaccine takes two weeks to reach its maximum

Average_Vaccination_Percentage_Israel = (Vaccinationsdf["Second_Dose_Percentage"]).mean()/100
Average_Vaccination_Percentage_Israel

0.1451510204081633

In [24]:
# Preparing the contingency table for two-sample hypothesis testing
# Please note the following assumptions
# The first row "Daily Covid Cases" contains values averaged from the Israeli National dataset
# The second row is not meaningful for our calculations  
# The third column of the third row "Total population at Risk" is estimated by the average number of daily Covid tests taken
# We assume that the population exposed to covid risks has a similar vaccination status as the gerneral Israeli public
# Thus, the first and second column is estimated by (Total Population at Risk*Average Israeli Vaccination Percentage)

Dict_NOT_WORKING = {'Vaxxed':[Daily_Cases_Vaccinated_Alpha,
                                        Average_Vaccination_Percentage_Israel*Daily_Polulation_at_Risk_Alpha], 
            'Unvaxxed': [Daily_Cases_Not_Vaccinated_Alpha,
                            (1 - Average_Vaccination_Percentage_Israel)*Daily_Polulation_at_Risk_Alpha],
                   'Total': [Daily_Cases_Not_Vaccinated_Alpha+Daily_Cases_Vaccinated_Alpha,
                            Daily_Polulation_at_Risk_Alpha ]}

NOT_WORKING = pd.DataFrame(Dict_NOT_WORKING, index = ['Daily Covid Cases by Vaxx Status',
                                              'Population at Risk by Vaxx Status'])
NOT_WORKING

#We can't get statistics for 'Not_Determined'. These data won't be collected
#by any databases

                                        Vaxxed      Unvaxxed         Total
Daily Covid Cases by Vaxx Status     66.102041   3013.510204   3079.612245
Population at Risk by Vaxx Status  9969.700799  58715.319609  68685.020408

In [27]:
#Hypothesis testing

#according to the contingency table displayed above, we derived that for our pythonthese testing
# x1 = 66.102041, x2 = 3013.510204
# p1 = 9969.700799, p2 = 58715.319609
# Ho: p1 = p2
# Ha: p1 < p2

#setup a significance level
SL = 0.05

#setup the numpy array for x1 and x2
number_of_incidences = np.array([66.102041, 3013.510204])

#setup the numpy array for p1 and p2
total_sample_sizes = np.array([9969.700799, 58715.319609])

# Compute test statistics and p-value
(test_stat, p_value) = proportions_ztest(number_of_incidences, total_sample_sizes, alternative= 'smaller')
print(test_stat)
print(p_value)

#printing the result:
if (p_value < 0.001): 
    print("There is very strong evidence against the null hypothesis." + "\n" +
    "The sample evidence suggests very strongly that fully vaccinated population" + "\n" +
    "have lower chances of being infected than the not fully vaccinated population.")
elif (p_value < 0.01):
    print("There is strong evidence against the null hypothesis.")
elif (p_value < SL):
    print("There is moderate evidence against the null hypothesis.")
else:
    print("Do not reject the null hypothesis. The sample evidence is in \
          accordance with the statement in the null hypothesis.")

-19.937797368034737
9.565238219571445e-89
There is very strong evidence against the null hypothesis.
The sample evidence suggests very strongly that fully vaccinated population
have lower chances of being infected than the not fully vaccinated population.